# Generated by Django 4.2.16 on 2024-11-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_description',
            field=models.FileField(blank=True, upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
