# Generated by Django 4.2.16 on 2024-11-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0002_candidate_job_description_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
