# Generated by Django 5.1.3 on 2025-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('hold', 'Hold'), ('registered', 'Registered')], default='registered', max_length=10),
        ),
    ]
