# Generated by Django 5.1.3 on 2024-11-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_description',
        ),
    ]
