# Generated by Django 5.1.3 on 2025-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0002_remove_candidate_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='interview_summary',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
