# Generated by Django 5.1.3 on 2025-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0002_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
