# Generated by Django 5.1.3 on 2025-02-11 07:43

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    # Get models
    Organization = apps.get_model("elexis", "Organization")
    from django.contrib.auth import get_user_model

    # Get environment variables
    org_name = os.getenv("ORG_NAME", "DefaultOrg")
    email = os.getenv("SUPERUSER_EMAIL", "admin@example.com")
    password = os.getenv("SUPERUSER_PASSWORD", "admin123")
    first_name = os.getenv("SUPERUSER_FIRST_NAME", "Admin")
    last_name = os.getenv("SUPERUSER_LAST_NAME", "User")
    
    # Create or get Organization
    organization = Organization.objects.get(org_name=org_name)  

    # # Create Superuser if not already exists
    User = get_user_model()
    if not User.objects.filter(email=email).exists():
        user =User(
            email=email,
            first_name=first_name,
            last_name=last_name,
            organization_id=str(organization.id),
            is_staff=True,
            is_superuser=True
        )
        user.set_password(password)
        user.save(force_insert=True)



class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('elexis', '0002_create_org_and_superuser'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
