# Generated by Django 5.1.3 on 2025-02-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0003_auto_20250211_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
