# Generated by Django 5.1.3 on 2025-02-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0004_job_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
