# Generated by Django 5.1.3 on 2025-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0005_candidate_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='experience',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='skills',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
