# Generated by Django 5.1.3 on 2025-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0006_interview_experience_interview_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='meeting_room',
            field=models.URLField(blank=True, null=True),
        ),
    ]
