# Generated by Django 5.1.3 on 2025-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0007_interview_meeting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(blank=True, default='Default Company', max_length=100),
        ),
    ]
