# Generated by Django 5.1.3 on 2025-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0008_alter_recruiter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='transcript',
            field=models.URLField(blank=True, null=True),
        ),
    ]
