# Generated by Django 5.1.3 on 2025-05-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0010_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('ended', 'Ended'), ('hold', 'Hold'), ('registered', 'Registered')], default='registered', max_length=10),
        ),
    ]
