# Generated by Django 5.1.3 on 2025-05-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0012_jobrequirement_jobrequiremnetevaluation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRequiremnetEvaluation',
            new_name='JobRequirementEvaluation',
        ),
    ]
