# Generated by Django 5.1.3 on 2025-05-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0013_rename_jobrequiremnetevaluation_jobrequirementevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirementevaluation',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='elexis.job'),
        ),
    ]
