# Generated by Django 5.1.3 on 2025-05-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0014_jobrequirementevaluation_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequirementevaluation',
            old_name='jobRequirement',
            new_name='job_requirement',
        ),
    ]
