# Generated by Django 5.1.3 on 2025-06-05 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0015_rename_jobrequirement_jobrequirementevaluation_job_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirementevaluation',
            name='interview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation', to='elexis.interview'),
        ),
    ]
