# Generated by Django 5.1.3 on 2025-06-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0016_jobrequirementevaluation_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirementevaluation',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation', to='elexis.interview'),
        ),
    ]
