# Generated by Django 5.1.3 on 2025-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0019_alter_jobrequirementevaluation_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='language',
            field=models.CharField(default='English', help_text='Language used in the interview', max_length=50),
        ),
    ]
