# Generated by Django 5.1.3 on 2025-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0020_interview_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], default='english', help_text='Language used in the interview', max_length=50),
        ),
    ]
