# Generated by Django 5.1.3 on 2025-06-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0021_alter_interview_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        )
    ]
