# Generated by Django 5.1.3 on 2025-06-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0022_alter_interview_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirementevaluation',
            name='interview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation', to='elexis.interview'),
        ),
    ]
