# Generated by Django 5.1.3 on 2025-06-20 05:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0022_alter_interview_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequirementevaluation',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluation', to='elexis.interview'),
        ),
        migrations.CreateModel(
            name='MaintaineceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.TextField()),
                ('user_display_text', models.TextField(default='Elexis is currently undergoing maintenance. We apologize for any inconvenience caused. Please check back later.')),
                ('is_draft', models.BooleanField(default=False, help_text='If True, this maintenance window is not yet active and will not be displayed to users.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Windows',
            },
        ),
    ]
