# Generated by Django 5.1.3 on 2025-06-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0023_alter_jobrequirementevaluation_interview'),
        ('elexis', '0023_alter_jobrequirementevaluation_interview_and_more'),
    ]

    operations = [
    ]
