# Generated by Django 5.1.3 on 2025-06-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0024_merge_20250620_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ecs_task_created',
            field=models.BooleanField(default=False),
        ),
    ]
