# Generated by Django 5.1.3 on 2025-06-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0025_interview_ecs_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_exempt_from_maintenance',
            field=models.BooleanField(default=False, help_text='If True, this organization is exempt from maintenance windows and will not be affected by them.'),
        ),
    ]
