# Generated by Django 5.1.3 on 2025-06-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0026_organization_is_exempt_from_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='reason_for_leaving_previous_job',
            field=models.TextField(blank=True, help_text='Reason for leaving the previous job', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ask_for_ctc_info',
            field=models.BooleanField(default=True, help_text='If True, candidates will be asked for their CTC information during the interview process.'),
        ),
        migrations.AddField(
            model_name='job',
            name='ask_for_language_preference',
            field=models.BooleanField(default=True, help_text='If True, candidates will be asked for their language preference during the interview process.'),
        ),
        migrations.AddField(
            model_name='job',
            name='ask_for_reason_for_leaving_previous_job',
            field=models.BooleanField(default=True, help_text='If True, candidates will be asked for the reason for leaving their previous job during the interview process.'),
        ),
    ]
