# Generated by Django 5.1.3 on 2025-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0027_interview_current_ctc_interview_expected_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='_allowed_interview_languages',
            field=models.CharField(default='english', help_text="Comma-separated list of allowed interview languages (e.g., 'english,hindi').", max_length=255),
        ),
    ]
