# Generated by Django 5.1.3 on 2025-06-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0028_job__allowed_interview_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ask_for_language_preference',
        ),
    ]
