# Generated by Django 5.1.3 on 2025-06-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0030_interviewquestions_jobquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestions',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='elexis.job'),
        ),
    ]
