# Generated by Django 5.1.3 on 2025-06-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0031_alter_jobquestions_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='_allowed_interview_languages',
            new_name='allowed_interview_languages',
        ),
    ]
