# Generated by Django 5.1.3 on 2025-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0032_rename__allowed_interview_languages_job_allowed_interview_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_embedding_id',
            field=models.CharField(blank=True, help_text='ID of the resume embedding in the vector database.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description_embedding_id',
            field=models.CharField(blank=True, help_text='ID of the job description embedding in the vector database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('ended', 'Ended'), ('hold', 'Hold'), ('registered', 'Registered'), ('not_joined', 'Not Joined')], default='registered', max_length=10),
        ),
    ]
