# Generated by Django 5.1.3 on 2025-07-28 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0034_jobmatchingresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatchingresume',
            name='score',
            field=models.DecimalField(decimal_places=10, help_text="Score indicating how well the candidate's resume matches the job description", max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
