# Generated by Django 5.1.3 on 2025-07-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0035_alter_jobmatchingresume_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmatchingresume',
            options={'ordering': ['-score']},
        ),
        migrations.AlterUniqueTogether(
            name='jobmatchingresume',
            unique_together={('job', 'candidate')},
        ),
    ]
