# Generated by Django 5.1.3 on 2025-07-30 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0037_inboundcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('candidate_onboard', 'Onboard'), ('seleted_for_interview', 'Selected for Interview'), ('scheduled', 'Interview Scheduled'), ('completed', 'Interview Completed')], default='candidate_onboard', help_text='Current stage of the candidate in the inbound process', max_length=50)),
                ('isArchieved', models.BooleanField(default=False, help_text='If True, this row is not the present state of the candidate in our interview process. He progressed or maybe archived.')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stages', to='elexis.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stages', to='elexis.job')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stages', to='elexis.organization')),
            ],
            options={
                'ordering': ['-created_date'],
                'unique_together': {('candidate', 'job', 'stage')},
            },
        ),
        migrations.DeleteModel(
            name='InboundCandidate',
        ),
    ]
