# Generated by Django 5.1.3 on 2025-07-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0038_candidatestages_delete_inboundcandidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateStages',
            new_name='CandidateStagesInJobView',
        ),
    ]
