# Generated by Django 5.1.3 on 2025-07-30 11:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0039_rename_candidatestages_candidatestagesinjobview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobmatchingresume',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobmatchingresume',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='jobmatchingresume',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobmatchingresume',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobmatchingresume',
            name='modified_by',
        ),
        migrations.CreateModel(
            name='JobMatchingResumeScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=10, help_text="Score indicating how well the candidate's resume matches the job description", max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stage', models.CharField(choices=[('candidate_onboard', 'Onboard'), ('seleted_for_interview', 'Selected for Interview'), ('scheduled', 'Interview Scheduled'), ('completed', 'Interview Completed')], default='candidate_onboard', help_text='Current stage of the candidate in the inbound process', max_length=50)),
                ('isArchieved', models.BooleanField(default=False, help_text='If True, this row is not the present state of the candidate in our interview process. He progressed or maybe archived.')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_resumes', to='elexis.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_resumes', to='elexis.job')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('job', 'candidate', 'stage')},
            },
        ),
        migrations.DeleteModel(
            name='CandidateStagesInJobView',
        ),
        migrations.DeleteModel(
            name='JobMatchingResume',
        ),
    ]
