# Generated by Django 5.1.3 on 2025-07-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0040_alter_jobmatchingresume_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmatchingresumescore',
            old_name='isArchieved',
            new_name='is_archieved',
        ),
    ]
