# Generated by Django 5.1.3 on 2025-07-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0041_rename_isarchieved_jobmatchingresumescore_is_archieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatchingresumescore',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_resumes', to='elexis.organization'),
        ),
    ]
