# Generated by Django 5.1.3 on 2025-07-31 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0042_jobmatchingresumescore_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatchingresumescore',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_resumes', to='elexis.organization'),
        ),
    ]
