# Generated by Django 5.1.3 on 2025-08-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0043_alter_jobmatchingresumescore_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatchingresumescore',
            name='stage',
            field=models.CharField(choices=[('candidate_onboard', 'Onboard'), ('selected_for_interview', 'Selected for Interview'), ('scheduled_interview', 'Interview Scheduled'), ('completed_interview', 'Interview Completed')], default='candidate_onboard', help_text='Current stage of the candidate in the inbound process', max_length=50),
        ),
    ]
