# Generated by Django 5.1.3 on 2025-08-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0044_alter_jobmatchingresumescore_stage'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='jobmatchingresumescore',
        #     unique_together={('job', 'candidate', 'stage', 'is_archieved')},
        # ),
    ]
