# Generated by Django 5.1.3 on 2025-08-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0045_alter_jobmatchingresumescore_unique_together'),
    ]

    operations = [
         migrations.AddField(
            model_name='interview',
            name='job_matching_resume_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interviews', to='elexis.jobmatchingresumescore'),
        ),
    ]
