# Generated by Django 5.1.3 on 2025-08-14 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0046_jobmatchingresumescore_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatchingresumescore',
            name='score',
            field=models.DecimalField(decimal_places=10, default=0.0, help_text="Score indicating how well the candidate's resume matches the job description", max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
