# Generated by Django 5.1.3 on 2025-08-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0049_add_jobresumematchingscore_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job_matching_resume_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='elexis.jobmatchingresumescore'),
        ),
    ]
