# Generated by Django 5.1.3 on 2025-08-15 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0050_alter_interview_job_matching_resume_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmatchingresumescore',
            old_name='is_archieved',
            new_name='is_archived',
        ),
        # migrations.AlterUniqueTogether(
        #     name='jobmatchingresumescore',
        #     unique_together=set(),
        # ),
    ]
