# Generated by Django 5.1.3 on 2025-08-15 07:12

from django.db import migrations



def set_default_embedding_ids(apps, schema_editor):
    
    Candidates = apps.get_model('elexis', 'Candidate')
    Jobs = apps.get_model('elexis', 'Job')

    for candidate in Candidates.objects.all():
        candidate.resume_embedding_id = f"resume-{candidate.id}"
        candidate.save(update_fields=["resume_embedding_id"])
    for job in Jobs.objects.all():
        job.job_description_embedding_id=f"job-{job.id}"
        job.save(update_fields=["job_description_embedding_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0051_rename_is_archieved_jobmatchingresumescore_is_archived_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_embedding_ids)
    ]
