# Generated by Django 5.1.3 on 2025-08-17 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0052_auto_20250815_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='jobmatchingresumescore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, help_text="Score indicating how well the candidate's resume matches the job description", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
