# Generated by Django 5.1.3 on 2025-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0053_alter_job_options_alter_jobmatchingresumescore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatchingresumescore',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
