# Generated by Django 5.1.3 on 2025-08-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0055_backgroundanalysis_directcomparison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringsignals',
            name='careerTrajectory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringsignals',
            name='prestigeFactors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringsignals',
            name='resumeQuality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringsignals',
            name='transitionEase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='overallRecommendation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolefitanalysis',
            name='experienceLevel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolefitanalysis',
            name='industryAlignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolefitanalysis',
            name='jobTitleMatch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
