# Generated by Django 5.1.3 on 2025-08-24 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0056_alter_hiringsignals_careertrajectory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijdresumematchingresponse',
            name='suggested_resumes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluations', to='elexis.candidate'),
        ),
        migrations.AlterField(
            model_name='aijdresumematchingresponse',
            name='job_matching_resume_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluations', to='elexis.jobmatchingresumescore'),
        ),
        migrations.CreateModel(
            name='SuggestedCandidates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('archive', 'Archive'), ('default', 'Default')], default='default', help_text='Current stage of the candidate in the Suggestion process', max_length=50)),
                ('aiResumeMatchingResponse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_candidates', to='elexis.aijdresumematchingresponse')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_candidates', to='elexis.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_candidates', to='elexis.job')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
