# Generated by Django 5.1.3 on 2025-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0057_aijdresumematchingresponse_suggested_resumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcandidates',
            name='lastComputed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
