# Generated by Django 5.1.3 on 2025-08-25 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0058_suggestedcandidates_lastcomputed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedcandidates',
            name='lastComputed',
        ),
        migrations.AlterField(
            model_name='suggestedcandidates',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_candidates', to='elexis.candidate'),
        ),
        migrations.AlterField(
            model_name='suggestedcandidates',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_candidates', to='elexis.job'),
        ),
    ]
