# Generated by Django 5.1.3 on 2025-09-03 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0059_remove_suggestedcandidates_lastcomputed_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='suggestedcandidates',
        #     name='stage',
        #     field=models.CharField(choices=[('archived', 'Archived'), ('default', 'Default')], default='default', help_text='Current stage of the candidate in the Suggestion process', max_length=50),
        # ),
        migrations.CreateModel(
            name='ECSApplicationAutoScalingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('scheduled_action_name', models.TextField()),
                ('min_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
