# Generated by Django 5.1.3 on 2025-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0060_alter_suggestedcandidates_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedcandidates',
            name='stage',
            field=models.CharField(choices=[('archived', 'Archived'), ('default', 'Default')], default='default', help_text='Current stage of the candidate in the Suggestion process', max_length=50),
        ),
    ]
