# Generated by Django 5.1.3 on 2025-09-25 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0061_alter_suggestedcandidates_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatchingresumescore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, help_text="Score indicating how well the candidate's resume matches the job description", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
