# Generated by Django 5.1.3 on 2025-12-05 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0062_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_date']},
        ),
        migrations.CreateModel(
            name='ResumeUploadTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('upload_type', models.CharField(choices=[('single_manual', 'Single Manual Entry'), ('single_resume', 'Single Resume Upload'), ('bulk', 'Bulk Upload')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_failed', 'Partially Failed')], default='pending', max_length=20)),
                ('batch_job_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('successful_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Associated job if candidates are being added to specific job', null=True, on_delete=django.db.models.deletion.CASCADE, to='elexis.job')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='has_modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_trackers', to='elexis.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
