# Generated by Django 5.1.3 on 2025-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elexis', '0063_alter_candidate_options_resumeuploadtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeuploadtracker',
            name='ai_failed_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeuploadtracker',
            name='ai_processed_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeuploadtracker',
            name='ai_successful_files',
            field=models.IntegerField(default=0),
        ),
    ]
